//mod print;
//mod vars;
//mod types;
//mod string;
mod string1;
//mod tuple;
//mod arrays;
//mod vectors;
//mod conditionals;
//mod loops;
//mod functions;
//mod pointers;
//mod structures;
//mod enums;
//mod cli;
//mod codeblocks;
//mod shadowing;
//mod references;
//mod reference_fun;
//mod test;
//mod input;
fn main() {
    //print::run();
    //vars::run();
    //types::run();
    //string::run();
    string1::run();
    //tuple::run();
    //arrays::run();
    //vectors::run();
    //conditionals::run();
    //loops::run();
    //functions::run();
    //pointers::run();
    //structures::run();
    //enums::run();
    //cli::run();
    //codeblocks::run();
    //shadowing::run();
    //references::run();
    //reference_fun::run();
    //test::run();
    //input::run();
}
